### PR TITLE
Added isEmpty method

### PR DESCRIPTION
**Pull request by churchofthought**
Based on my macro code from here: https://gist.github.com/iandrewfuchs/5520045

Let me know what you think. Cheers!

### CODE REVIEW

**Comment by robb** [comment]
Sorry that this took so long to be addressed. I took the liberty to make some changes (I don't think `NSNull.null` or `@NO` should be considered ~~false~~ empty) and threw in a test.

Thanks!

Edit: considered empty, not false

**Comment by churchofthought** [comment]
Robb, you may want to consider turning Underscore.m into Underscore.mm
(Objective C++) for faster and more performant, robust code. With function
overloading, many procedures would be a ton faster. For an example of a
performant isEmpty implementation created for use in my non-coalescing
null/OR macro, checkout this:

https://gist.github.com/iandrewfuchs/5520045

Let me know what you think.

Cheers,
   Andy

**Comment by robb** [comment]
Hmm, that would mean that code that calls Underscore.m has to be Objective-C++ as well right?

I'm also working on [Asterism](http://github.com/robb/Asterism) which uses clang's C function overloading extension to achieve a similar effect (and more typesafety!) Would that work for you, too?

**Comment by churchofthought** [comment]
Wow did not have any idea Clang supported that! Awesome extension! :-)

Recently I've been working with some MSVC code and god- the horror of
missing GNU extensions....-_-
Things like int anArr[dynamicLength] instead have to be malloced
out...Extensions are wonderful!

Yeah, I suppose something like that could be used instead of the C++
overloading, because we wouldn't want to require people to make their whole
projects Objective C++, that'd create quite a headache for users.

Asterism looks great, functional programming is sorely missing in ObjC.

Cheers,
    Andy

**Comment by robb** [comment]
Cool, i'm throwing an ASTEmpty together right now :)

**Comment by churchofthought** [comment]
Sweet!

**Pull request closed without merging**
