### PR TITLE
fix compilation error for ARC projects that mix non-ARC code when import...

### PR DESCRIPTION
**Pull request by s12chung**
...ing from the prefix header

For Issue #26

### CODE REVIEW

**Comment by s12chung** [comment]
Note, I did not test for non-ARC projects. Theoretically it works....

**Comment by robb** [comment]
Just tried using this Podfile

``` ruby
xcodeproj './non-arc.xcodeproj'
platform :ios, :deployment_target => 6.0

pod 'Underscore.m', :git => 'https://github.com/s12chung/Underscore.m', :branch => 'development'
```

in a non-arc project and it worked fine :+1:

**Comment by s12chung** [comment]
awesome :) thanks for checking and your quickness.

**Comment by robb** [comment]
Thanks for contributing!

**Pull request merged**
